### ISSUE TITLE
be able to access AWS resources by there tag name

### ISSUE THREAD

**Issue by neillturner** [stelligent/serverspec-aws-resources#19]
These resources would be really useful for verifying AWS resources created via cloud formation or terraform. 
It could be used with test-kitchen to provide a TDD approach to cloud orchestration. 
It would be better is we could refer to aws resources by name rather than the internal id.
for example a VPC might be created with a name tag of "privatevpc" and it would be better if we could write 
serverspec like: 
```
 describe vpc('privatevpc') do
    it { should be_default_tenancy }
  end
```
instead of 
```
 describe vpc('vpc-12345') do
    it { should be_default_tenancy }
  end
```

**Comment by ghost** [comment]
Neil, I haven't done any development on this project in a good bit of time.  The project: https://github.com/k1LoW/awspec does a pretty good job of realizing the goals I had for this one (and I've used awspec successfully on a number of gigs)

**Comment by neillturner** [comment]
thanks for that i saw several projects out there so thanks for your recommendation
